apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: backstage-pgcluster
  labels:
    app.kubernetes.io/name: backstage
    app.kubernetes.io/component: pgcluster
    app.kubernetes.io/instance: ${bs_app_name}
spec:
  instances: 2
  storage:
    size: 1Gi